repos:
- repo: https://github.com/iancrosby050/pre-commit-terraform
  rev: v1.70.1
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_docs
    args: ["--args=--sort-by required"]