apiVersion: v1
kind: Pod
metadata:
  name: kuards
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuards
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP